inputs:
  os:
    description: "One of the supported platforms: windows"
    required: true
  arch:
    description: "The architecture to build for: x64, arm64"
    required: true
runs:
  using: composite
  steps:
  - name: Set up node & dependencies
    uses: actions/setup-node@v4
    with:
      node-version: 22
      cache: "npm"
  - name: Install dependencies
    shell: bash
    run: npm ci
  - name: Run Linux server build
    env:
      MATRIX_ARCH: ${{ inputs.arch }}
    shell: bash
    run: |
      npm run chore:update-build-info
      npm run package
  - name: Prepare artifacts
    shell: bash
    run: |
      mkdir -p upload
      file=$(find dist -name '*.tar.xz' -print -quit)
      name=${{ github.ref_name }}
      cp "$file" "upload/TriliumNextNotes-Server-${name//\//-}-${{ inputs.os }}-${{ inputs.arch }}.tar.xz"
