name: Release
on:
    push:
        tags:
            - 'v*'
jobs:
    publish-package:
        name: Publish package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  always-auth: true
            - run: |
                corepack enable &&
                corepack install
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Publish package
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
