import { normalizeMimeTypeForCKEditor } from "@triliumnext/commons";
import type { LanguageFn } from "@highlightjs/cdn-assets/es/core.js";

type MimeRecord = Record<string, (() => Promise<{ default: LanguageFn}>) | null>;

const byMimeType: MimeRecord = {
    "text/plain": () => import("@highlightjs/cdn-assets/lib/languages/plaintext"),
    "application/dart": () => import("@highlightjs/cdn-assets/lib/languages/dart"),
    "application/edn": () => import("@highlightjs/cdn-assets/lib/languages/clojure"),
    "application/javascript;env=backend": () => import("@highlightjs/cdn-assets/lib/languages/javascript"),
    "application/javascript;env=frontend": () => import("@highlightjs/cdn-assets/lib/languages/javascript"),
    "application/json": () => import("@highlightjs/cdn-assets/lib/languages/json"),
    "application/ld+json": () => import("@highlightjs/cdn-assets/lib/languages/json"),
    "application/mbox": null,
    "application/n-triples": null,
    "application/pgp": null,
    "application/sieve": null,
    "application/sparql-query": null,
    "application/typescript": () => import("@highlightjs/cdn-assets/lib/languages/typescript"),
    "application/x-aspx": null,
    "application/x-bat": () => import("@highlightjs/cdn-assets/lib/languages/dos"),
    "application/x-cypher-query": () => import("highlightjs-cypher"),
    "application/x-ejs": null,
    "application/x-erb": () => import("@highlightjs/cdn-assets/lib/languages/erb"),
    "application/x-jsp": () => import("@highlightjs/cdn-assets/lib/languages/java"),
    "application/x-powershell": () => import("@highlightjs/cdn-assets/lib/languages/powershell"),
    "application/xml-dtd": () => import("@highlightjs/cdn-assets/lib/languages/xml"),
    "application/xquery": () => import("@highlightjs/cdn-assets/lib/languages/xquery"),
    "message/http": () => import("@highlightjs/cdn-assets/lib/languages/http"),
    "text/apl": null,
    "text/coffeescript": () => import("@highlightjs/cdn-assets/lib/languages/coffeescript"),
    "text/css": () => import("@highlightjs/cdn-assets/lib/languages/css"),
    "text/html": () => import("@highlightjs/cdn-assets/lib/languages/xml"),
    "text/jinja2": () => import("@highlightjs/cdn-assets/lib/languages/django"),
    "text/jsx": () => import("@highlightjs/cdn-assets/lib/languages/javascript"),
    "text/mirc": () => import("./languages/mirc.js"),
    "text/tiki": null,
    "text/troff": null,
    "text/turtle": null,
    "text/typescript-jsx": () => import("@highlightjs/cdn-assets/lib/languages/typescript"),
    "text/vbscript": () => import("@highlightjs/cdn-assets/lib/languages/vbscript"),
    "text/velocity": null,
    "text/vnd.mermaid": null,
    "text/mermaid": null,
    "text/x-asm-mips": () => import("@highlightjs/cdn-assets/lib/languages/mipsasm"),
    "text/x-asterisk": null,
    "text/x-brainfuck": () => import("@highlightjs/cdn-assets/lib/languages/brainfuck"),
    "text/x-c++src": () => import("@highlightjs/cdn-assets/lib/languages/cpp"),
    "text/x-cassandra": null,
    "text/x-clojure": () => import("@highlightjs/cdn-assets/lib/languages/clojure"),
    "text/x-clojurescript": () => import("@highlightjs/cdn-assets/lib/languages/clojure"),
    "text/x-cmake": () => import("@highlightjs/cdn-assets/lib/languages/cmake"),
    "text/x-cobol": () => import("highlightjs-cobol"),
    "text/x-common-lisp": () => import("@highlightjs/cdn-assets/lib/languages/lisp"),
    "text/x-crystal": () => import("@highlightjs/cdn-assets/lib/languages/crystal"),
    "text/x-csharp": () => import("@highlightjs/cdn-assets/lib/languages/csharp"),
    "text/x-csrc": () => import("@highlightjs/cdn-assets/lib/languages/c"),
    "text/x-cython": null,
    "text/x-d": () => import("@highlightjs/cdn-assets/lib/languages/d"),
    "text/x-diff": () => import("@highlightjs/cdn-assets/lib/languages/diff"),
    "text/x-django": () => import("@highlightjs/cdn-assets/lib/languages/django"),
    "text/x-dockerfile": () => import("@highlightjs/cdn-assets/lib/languages/dockerfile"),
    "text/x-dylan": () => import("./languages/dylan.js"),
    "text/x-ebnf": () => import("@highlightjs/cdn-assets/lib/languages/ebnf"),
    "text/x-ecl": null,
    "text/x-eiffel": null,
    "text/x-elm": () => import("@highlightjs/cdn-assets/lib/languages/elm"),
    "text/x-erlang": () => import("@highlightjs/cdn-assets/lib/languages/erlang"),
    "text/x-esper": null,
    "text/x-factor": null,
    "text/x-fcl": null,
    "text/x-feature": () => import("@highlightjs/cdn-assets/lib/languages/gherkin"),
    "text/x-forth": null,
    "text/x-fortran": () => import("@highlightjs/cdn-assets/lib/languages/fortran"),
    "text/x-fsharp": () => import("@highlightjs/cdn-assets/lib/languages/fsharp"),
    "text/x-gas": null,
    "text/x-gdscript": () => import("@exercism/highlightjs-gdscript"),
    "text/x-gfm": () => import("@highlightjs/cdn-assets/lib/languages/markdown"),
    "text/x-go": () => import("@highlightjs/cdn-assets/lib/languages/go"),
    "text/x-groovy": () => import("@highlightjs/cdn-assets/lib/languages/groovy"),
    "text/x-gss": null,
    "text/x-haml": () => import("@highlightjs/cdn-assets/lib/languages/haml"),
    "text/x-haskell": () => import("@highlightjs/cdn-assets/lib/languages/haskell"),
    "text/x-haxe": () => import("@highlightjs/cdn-assets/lib/languages/haxe"),
    "text/x-hcl": () => import("./languages/terraform.js"),
    "text/x-hxml": null,
    "text/x-idl": null,
    "text/x-java": () => import("@highlightjs/cdn-assets/lib/languages/java"),
    "text/x-julia": () => import("@highlightjs/cdn-assets/lib/languages/julia"),
    "text/x-kotlin": () => import("@highlightjs/cdn-assets/lib/languages/kotlin"),
    "text/x-latex": () => import("@highlightjs/cdn-assets/lib/languages/latex"),
    "text/x-less": () => import("@highlightjs/cdn-assets/lib/languages/less"),
    "text/x-literate-haskell": null,
    "text/x-livescript": () => import("@highlightjs/cdn-assets/lib/languages/livescript"),
    "text/x-lua": () => import("@highlightjs/cdn-assets/lib/languages/lua"),
    "text/x-mariadb": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-markdown": () => import("@highlightjs/cdn-assets/lib/languages/markdown"),
    "text/x-mathematica": () => import("@highlightjs/cdn-assets/lib/languages/mathematica"),
    "text/x-modelica": null,
    "text/x-mscgen": null,
    "text/x-msgenny": null,
    "text/x-mssql": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-mumps": null,
    "text/x-mysql": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-nix": () => import("@highlightjs/cdn-assets/lib/languages/nix"),
    "text/x-nginx-conf": () => import("@highlightjs/cdn-assets/lib/languages/nginx"),
    "text/x-nsis": () => import("@highlightjs/cdn-assets/lib/languages/nsis"),
    "text/x-objectivec": () => import("@highlightjs/cdn-assets/lib/languages/objectivec"),
    "text/x-ocaml": () => import("@highlightjs/cdn-assets/lib/languages/ocaml"),
    "text/x-octave": null,
    "text/x-oz": null,
    "text/x-pascal": () => import("@highlightjs/cdn-assets/lib/languages/delphi"),
    "text/x-perl": () => import("@highlightjs/cdn-assets/lib/languages/perl"),
    "text/x-pgsql": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-php": () => import("@highlightjs/cdn-assets/lib/languages/php"),
    "text/x-pig": null,
    "text/x-plsql": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-properties": () => import("@highlightjs/cdn-assets/lib/languages/properties"),
    "text/x-protobuf": () => import("@highlightjs/cdn-assets/lib/languages/protobuf"),
    "text/x-pug": null,
    "text/x-puppet": () => import("@highlightjs/cdn-assets/lib/languages/puppet"),
    "text/x-python": () => import("@highlightjs/cdn-assets/lib/languages/python"),
    "text/x-q": () => import("@highlightjs/cdn-assets/lib/languages/q"),
    "text/x-rpm-changes": null,
    "text/x-rpm-spec": () => import("./languages/rpm-specfile.js"),
    "text/x-rsrc": () => import("@highlightjs/cdn-assets/lib/languages/r"),
    "text/x-rst": null,
    "text/x-ruby": () => import("@highlightjs/cdn-assets/lib/languages/ruby"),
    "text/x-rustsrc": () => import("@highlightjs/cdn-assets/lib/languages/rust"),
    "text/x-sas": () => import("@highlightjs/cdn-assets/lib/languages/sas"),
    "text/x-sass": () => import("@highlightjs/cdn-assets/lib/languages/scss"),
    "text/x-scala": () => import("@highlightjs/cdn-assets/lib/languages/scala"),
    "text/x-scheme": () => import("@highlightjs/cdn-assets/lib/languages/scheme"),
    "text/x-scss": () => import("@highlightjs/cdn-assets/lib/languages/scss"),
    "text/x-sh": () => import("@highlightjs/cdn-assets/lib/languages/bash"),
    "text/x-slim": null,
    "text/x-smarty": null,
    "text/x-sml": () => import("@highlightjs/cdn-assets/lib/languages/sml"),
    "text/x-solr": null,
    "text/x-soy": null,
    "text/x-spreadsheet": null,
    "text/x-sql": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-sqlite;schema=trilium": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-sqlite": () => import("@highlightjs/cdn-assets/lib/languages/sql"),
    "text/x-squirrel": null,
    "text/x-stex": null,
    "text/x-stsrc": () => import("@highlightjs/cdn-assets/lib/languages/smalltalk"),
    "text/x-styl": () => import("@highlightjs/cdn-assets/lib/languages/stylus"),
    "text/x-swift": () => import("@highlightjs/cdn-assets/lib/languages/swift"),
    "text/x-systemverilog": () => import("@highlightjs/cdn-assets/lib/languages/verilog"),
    "text/x-tcl": () => import("@highlightjs/cdn-assets/lib/languages/tcl"),
    "text/x-textile": null,
    "text/x-tiddlywiki": null,
    "text/x-toml": () => import("@highlightjs/cdn-assets/lib/languages/ini"),
    "text/x-tornado": null,
    "text/x-ttcn-asn": null,
    "text/x-ttcn-cfg": null,
    "text/x-ttcn": () => import("./languages/ttcn3.js"),
    "text/x-twig": () => import("@highlightjs/cdn-assets/lib/languages/twig"),
    "text/x-vb": () => import("@highlightjs/cdn-assets/lib/languages/vbnet"),
    "text/x-verilog": () => import("@highlightjs/cdn-assets/lib/languages/verilog"),
    "text/x-vhdl": () => import("@highlightjs/cdn-assets/lib/languages/vhdl"),
    "text/x-vue": null,
    "text/x-webidl": null,
    "text/x-xu": null,
    "text/x-yacas": null,
    "text/x-yaml": () => import("@highlightjs/cdn-assets/lib/languages/yaml"),
    "text/x-z80": null,
    "text/xml": () => import("@highlightjs/cdn-assets/lib/languages/xml"),
}

const normalizedByMimeType: MimeRecord = {};
for (const [mimeType, loader] of Object.entries(byMimeType)) {
    const normalizedMimeType = normalizeMimeTypeForCKEditor(mimeType);
    normalizedByMimeType[normalizedMimeType] = loader;
}

export default normalizedByMimeType;
