import type { LanguageFn } from "highlight.js";

interface Mapping {
    loader: Promise<{ default: LanguageFn}>;
    alias: string;
}

const byMimeType: Record<string, (Mapping | null)> = {
    "text/plain": { loader: import("highlight.js/lib/languages/plaintext.js"), alias: "plaintext" },
    "application/dart": { loader: import("highlight.js/lib/languages/dart.js"), alias: "dart" },
    "application/edn": null,
    "application/javascript;env=backend": { loader: import("highlight.js/lib/languages/javascript.js"), alias: "javascript" },
    "application/javascript;env=frontend": { loader: import("highlight.js/lib/languages/javascript.js"), alias: "javascript" },
    "application/json": { loader: import("highlight.js/lib/languages/json.js"), alias: "json" },
    "application/ld+json": { loader: import("highlight.js/lib/languages/json.js"), alias: "json" },
    "application/mbox": null,
    "application/n-triples": null,
    "application/pgp": null,
    "application/sieve": null,
    "application/sparql-query": null,
    "application/typescript": { loader: import("highlight.js/lib/languages/typescript.js"), alias: "typescript" },
    "application/x-aspx": null,
    "application/x-bat": { loader: import("highlight.js/lib/languages/dos.js"), alias: "bat" },
    "application/x-cypher-query": null,
    "application/x-ejs": null,
    "application/x-erb": { loader: import("highlight.js/lib/languages/erb.js"), alias: "erb" },
    "application/x-jsp": { loader: import("highlight.js/lib/languages/java.js"), alias: "java" },
    "application/x-powershell": { loader: import("highlight.js/lib/languages/powershell.js"), alias: "powershell" },
    "application/xml-dtd": null,
    "application/xquery": { loader: import("highlight.js/lib/languages/xquery.js"), alias: "xquery" },
    "message/http": { loader: import("highlight.js/lib/languages/http.js"), alias: "http" },
    "text/apl": null,
    "text/coffeescript": { loader: import("highlight.js/lib/languages/coffeescript.js"), alias: "coffeescript" },
    "text/css": { loader: import("highlight.js/lib/languages/css.js"), alias: "css" },
    "text/html": { loader: import("highlight.js/lib/languages/xml.js"), alias: "html" },
    "text/jinja2": null,
    "text/jsx": { loader: import("highlight.js/lib/languages/javascript.js"), alias: "javascript" },
    "text/mirc": null,
    "text/tiki": null,
    "text/troff": null,
    "text/turtle": null,
    "text/typescript-jsx": { loader: import("highlight.js/lib/languages/typescript.js"), alias: "typescript" },
    "text/vbscript": { loader: import("highlight.js/lib/languages/vbscript.js"), alias: "vbscript" },
    "text/velocity": null,
    "text/vnd.mermaid": null,
    "text/mermaid": null,
    "text/x-asm-mips": { loader: import("highlight.js/lib/languages/mipsasm.js"), alias: "mipsasm" },
    "text/x-asterisk": null,
    "text/x-brainfuck": { loader: import("highlight.js/lib/languages/brainfuck.js"), alias: "brainfuck" },
    "text/x-c++src": { loader: import("highlight.js/lib/languages/cpp.js"), alias: "cpp" },
    "text/x-cassandra": null,
    "text/x-clojure": { loader: import("highlight.js/lib/languages/clojure.js"), alias: "clojure" },
    "text/x-clojurescript": null,
    "text/x-cmake": { loader: import("highlight.js/lib/languages/cmake.js"), alias: "cmake" },
    "text/x-cobol": null,
    "text/x-common-lisp": { loader: import("highlight.js/lib/languages/lisp.js"), alias: "lisp" },
    "text/x-crystal": { loader: import("highlight.js/lib/languages/crystal.js"), alias: "crystal" },
    "text/x-csharp": { loader: import("highlight.js/lib/languages/csharp.js"), alias: "csharp" },
    "text/x-csrc": { loader: import("highlight.js/lib/languages/c.js"), alias: "c" },
    "text/x-cython": null,
    "text/x-d": { loader: import("highlight.js/lib/languages/d.js"), alias: "d" },
    "text/x-diff": { loader: import("highlight.js/lib/languages/diff.js"), alias: "diff" },
    "text/x-django": { loader: import("highlight.js/lib/languages/django.js"), alias: "django" },
    "text/x-dockerfile": { loader: import("highlight.js/lib/languages/dockerfile.js"), alias: "dockerfile" },
    "text/x-dylan": null,
    "text/x-ebnf": { loader: import("highlight.js/lib/languages/ebnf.js"), alias: "ebnf" },
    "text/x-ecl": null,
    "text/x-eiffel": null,
    "text/x-elm": { loader: import("highlight.js/lib/languages/elm.js"), alias: "elm" },
    "text/x-erlang": { loader: import("highlight.js/lib/languages/erlang.js"), alias: "erlang" },
    "text/x-esper": null,
    "text/x-factor": null,
    "text/x-fcl": null,
    "text/x-feature": { loader: import("highlight.js/lib/languages/gherkin.js"), alias: "gherkin" },
    "text/x-forth": null,
    "text/x-fortran": { loader: import("highlight.js/lib/languages/fortran.js"), alias: "fortran" },
    "text/x-fsharp": { loader: import("highlight.js/lib/languages/fsharp.js"), alias: "fsharp" },
    "text/x-gas": null,
    "text/x-gdscript": null,
    "text/x-gfm": { loader: import("highlight.js/lib/languages/markdown.js"), alias: "markdown" },
    "text/x-go": { loader: import("highlight.js/lib/languages/go.js"), alias: "go" },
    "text/x-groovy": { loader: import("highlight.js/lib/languages/groovy.js"), alias: "groovy" },
    "text/x-gss": null,
    "text/x-haml": { loader: import("highlight.js/lib/languages/haml.js"), alias: "haml" },
    "text/x-haskell": { loader: import("highlight.js/lib/languages/haskell.js"), alias: "haskell" },
    "text/x-haxe": { loader: import("highlight.js/lib/languages/haxe.js"), alias: "haxe" },
    "text/x-hcl": { loader: import("./languages/terraform.js"), alias: "terraform" },
    "text/x-hxml": null,
    "text/x-idl": null,
    "text/x-java": { loader: import("highlight.js/lib/languages/java.js"), alias: "java" },
    "text/x-julia": { loader: import("highlight.js/lib/languages/julia.js"), alias: "julia" },
    "text/x-kotlin": { loader: import("highlight.js/lib/languages/kotlin.js"), alias: "kotlin" },
    "text/x-latex": { loader: import("highlight.js/lib/languages/latex.js"), alias: "latex" },
    "text/x-less": { loader: import("highlight.js/lib/languages/less.js"), alias: "less" },
    "text/x-literate-haskell": null,
    "text/x-livescript": { loader: import("highlight.js/lib/languages/livescript.js"), alias: "livescript" },
    "text/x-lua": { loader: import("highlight.js/lib/languages/lua.js"), alias: "lua" },
    "text/x-mariadb": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-markdown": { loader: import("highlight.js/lib/languages/markdown.js"), alias: "markdown" },
    "text/x-mathematica": { loader: import("highlight.js/lib/languages/mathematica.js"), alias: "mathematica" },
    "text/x-modelica": null,
    "text/x-mscgen": null,
    "text/x-msgenny": null,
    "text/x-mssql": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-mumps": null,
    "text/x-mysql": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-nix": { loader: import("highlight.js/lib/languages/nix.js"), alias: "nix" },
    "text/x-nginx-conf": { loader: import("highlight.js/lib/languages/nginx.js"), alias: "nginx" },
    "text/x-nsis": { loader: import("highlight.js/lib/languages/nsis.js"), alias: "nsis" },
    "text/x-objectivec": { loader: import("highlight.js/lib/languages/objectivec.js"), alias: "objectivec" },
    "text/x-ocaml": { loader: import("highlight.js/lib/languages/ocaml.js"), alias: "ocaml" },
    "text/x-octave": null,
    "text/x-oz": null,
    "text/x-pascal": { loader: import("highlight.js/lib/languages/delphi.js"), alias: "delphi" },
    "text/x-perl": null,
    "text/x-pgsql": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-php": { loader: import("highlight.js/lib/languages/php.js"), alias: "php" },
    "text/x-pig": null,
    "text/x-plsql": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-properties": { loader: import("highlight.js/lib/languages/properties.js"), alias: "properties" },
    "text/x-protobuf": { loader: import("highlight.js/lib/languages/protobuf.js"), alias: "protobuf" },
    "text/x-pug": null,
    "text/x-puppet": { loader: import("highlight.js/lib/languages/puppet.js"), alias: "puppet" },
    "text/x-python": { loader: import("highlight.js/lib/languages/python.js"), alias: "python" },
    "text/x-q": { loader: import("highlight.js/lib/languages/q.js"), alias: "q" },
    "text/x-rpm-changes": null,
    "text/x-rpm-spec": null,
    "text/x-rsrc": { loader: import("highlight.js/lib/languages/r.js"), alias: "r" },
    "text/x-rst": null,
    "text/x-ruby": { loader: import("highlight.js/lib/languages/ruby.js"), alias: "ruby" },
    "text/x-rustsrc": { loader: import("highlight.js/lib/languages/rust.js"), alias: "rust" },
    "text/x-sas": { loader: import("highlight.js/lib/languages/sas.js"), alias: "sas" },
    "text/x-sass": { loader: import("highlight.js/lib/languages/scss.js"), alias: "scss" },
    "text/x-scala": null,
    "text/x-scheme": null,
    "text/x-scss": { loader: import("highlight.js/lib/languages/scss.js"), alias: "scss" },
    "text/x-sh": { loader: import("highlight.js/lib/languages/bash.js"), alias: "bash" },
    "text/x-slim": null,
    "text/x-smarty": null,
    "text/x-sml": { loader: import("highlight.js/lib/languages/sml.js"), alias: "sml" },
    "text/x-solr": null,
    "text/x-soy": null,
    "text/x-spreadsheet": null,
    "text/x-sql": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-sqlite;schema=trilium": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-sqlite": { loader: import("highlight.js/lib/languages/sql.js"), alias: "sql" },
    "text/x-squirrel": null,
    "text/x-stex": null,
    "text/x-stsrc": { loader: import("highlight.js/lib/languages/smalltalk.js"), alias: "smalltalk" },
    "text/x-styl": { loader: import("highlight.js/lib/languages/stylus.js"), alias: "stylus" },
    "text/x-swift": null,
    "text/x-systemverilog": null,
    "text/x-tcl": { loader: import("highlight.js/lib/languages/tcl.js"), alias: "tcl" },
    "text/x-textile": null,
    "text/x-tiddlywiki": null,
    "text/x-toml": { loader: import("highlight.js/lib/languages/ini.js"), alias: "ini" },
    "text/x-tornado": null,
    "text/x-ttcn-asn": null,
    "text/x-ttcn-cfg": null,
    "text/x-ttcn": null,
    "text/x-twig": { loader: import("highlight.js/lib/languages/twig.js"), alias: "twig" },
    "text/x-vb": { loader: import("highlight.js/lib/languages/vbnet.js"), alias: "vbnet" },
    "text/x-verilog": { loader: import("highlight.js/lib/languages/verilog.js"), alias: "verilog" },
    "text/x-vhdl": { loader: import("highlight.js/lib/languages/vhdl.js"), alias: "vhdl" },
    "text/x-vue": null,
    "text/x-webidl": null,
    "text/x-xu": null,
    "text/x-yacas": null,
    "text/x-yaml": { loader: import("highlight.js/lib/languages/yaml.js"), alias: "yaml" },
    "text/x-z80": null,
    "text/xml": { loader: import("highlight.js/lib/languages/xml.js"), alias: "xml" },
}

export default byMimeType;
