import { normalizeMimeTypeForCKEditor } from "@triliumnext/commons";
import type { LanguageFn } from "@highlightjs/cdn-assets/es/core.js";

type MimeRecord = Record<string, (() => Promise<{ default: LanguageFn}>) | null>;

const byMimeType: MimeRecord = {
    "text/plain": () => import("@highlightjs/cdn-assets/languages/plaintext.min.js"),
    "application/dart": () => import("@highlightjs/cdn-assets/languages/dart.min.js"),
    "application/edn": () => import("@highlightjs/cdn-assets/languages/clojure.min.js"),
    "application/javascript;env=backend": () => import("@highlightjs/cdn-assets/languages/javascript.min.js"),
    "application/javascript;env=frontend": () => import("@highlightjs/cdn-assets/languages/javascript.min.js"),
    "application/json": () => import("@highlightjs/cdn-assets/languages/json.min.js"),
    "application/ld+json": () => import("@highlightjs/cdn-assets/languages/json.min.js"),
    "application/mbox": null,
    "application/n-triples": null,
    "application/pgp": null,
    "application/sieve": null,
    "application/sparql-query": null,
    "application/typescript": () => import("@highlightjs/cdn-assets/languages/typescript.min.js"),
    "application/x-aspx": null,
    "application/x-bat": () => import("@highlightjs/cdn-assets/languages/dos.min.js"),
    "application/x-cypher-query": () => import("highlightjs-cypher"),
    "application/x-ejs": null,
    "application/x-erb": () => import("@highlightjs/cdn-assets/languages/erb.min.js"),
    "application/x-jsp": () => import("@highlightjs/cdn-assets/languages/java.min.js"),
    "application/x-powershell": () => import("@highlightjs/cdn-assets/languages/powershell.min.js"),
    "application/xml-dtd": () => import("@highlightjs/cdn-assets/languages/xml.min.js"),
    "application/xquery": () => import("@highlightjs/cdn-assets/languages/xquery.min.js"),
    "message/http": () => import("@highlightjs/cdn-assets/languages/http.min.js"),
    "text/apl": null,
    "text/coffeescript": () => import("@highlightjs/cdn-assets/languages/coffeescript.min.js"),
    "text/css": () => import("@highlightjs/cdn-assets/languages/css.min.js"),
    "text/html": () => import("@highlightjs/cdn-assets/languages/xml.min.js"),
    "text/jinja2": () => import("@highlightjs/cdn-assets/languages/django.min.js"),
    "text/jsx": () => import("@highlightjs/cdn-assets/languages/javascript.min.js"),
    "text/mirc": () => import("./languages/mirc.js"),
    "text/tiki": null,
    "text/troff": null,
    "text/turtle": null,
    "text/typescript-jsx": () => import("@highlightjs/cdn-assets/languages/typescript.min.js"),
    "text/vbscript": () => import("@highlightjs/cdn-assets/languages/vbscript.min.js"),
    "text/velocity": null,
    "text/vnd.mermaid": null,
    "text/mermaid": null,
    "text/x-asm-mips": () => import("@highlightjs/cdn-assets/languages/mipsasm.min.js"),
    "text/x-asterisk": null,
    "text/x-brainfuck": () => import("@highlightjs/cdn-assets/languages/brainfuck.min.js"),
    "text/x-c++src": () => import("@highlightjs/cdn-assets/languages/cpp.min.js"),
    "text/x-cassandra": null,
    "text/x-clojure": () => import("@highlightjs/cdn-assets/languages/clojure.min.js"),
    "text/x-clojurescript": () => import("@highlightjs/cdn-assets/languages/clojure.min.js"),
    "text/x-cmake": () => import("@highlightjs/cdn-assets/languages/cmake.min.js"),
    "text/x-cobol": () => import("highlightjs-cobol"),
    "text/x-common-lisp": () => import("@highlightjs/cdn-assets/languages/lisp.min.js"),
    "text/x-crystal": () => import("@highlightjs/cdn-assets/languages/crystal.min.js"),
    "text/x-csharp": () => import("@highlightjs/cdn-assets/languages/csharp.min.js"),
    "text/x-csrc": () => import("@highlightjs/cdn-assets/languages/c.min.js"),
    "text/x-cython": null,
    "text/x-d": () => import("@highlightjs/cdn-assets/languages/d.min.js"),
    "text/x-diff": () => import("@highlightjs/cdn-assets/languages/diff.min.js"),
    "text/x-django": () => import("@highlightjs/cdn-assets/languages/django.min.js"),
    "text/x-dockerfile": () => import("@highlightjs/cdn-assets/languages/dockerfile.min.js"),
    "text/x-dylan": () => import("./languages/dylan.js"),
    "text/x-ebnf": () => import("@highlightjs/cdn-assets/languages/ebnf.min.js"),
    "text/x-ecl": null,
    "text/x-eiffel": null,
    "text/x-elm": () => import("@highlightjs/cdn-assets/languages/elm.min.js"),
    "text/x-erlang": () => import("@highlightjs/cdn-assets/languages/erlang.min.js"),
    "text/x-esper": null,
    "text/x-factor": null,
    "text/x-fcl": null,
    "text/x-feature": () => import("@highlightjs/cdn-assets/languages/gherkin.min.js"),
    "text/x-forth": null,
    "text/x-fortran": () => import("@highlightjs/cdn-assets/languages/fortran.min.js"),
    "text/x-fsharp": () => import("@highlightjs/cdn-assets/languages/fsharp.min.js"),
    "text/x-gas": null,
    "text/x-gdscript": () => import("@exercism/highlightjs-gdscript"),
    "text/x-gfm": () => import("@highlightjs/cdn-assets/languages/markdown.min.js"),
    "text/x-go": () => import("@highlightjs/cdn-assets/languages/go.min.js"),
    "text/x-groovy": () => import("@highlightjs/cdn-assets/languages/groovy.min.js"),
    "text/x-gss": null,
    "text/x-haml": () => import("@highlightjs/cdn-assets/languages/haml.min.js"),
    "text/x-haskell": () => import("@highlightjs/cdn-assets/languages/haskell.min.js"),
    "text/x-haxe": () => import("@highlightjs/cdn-assets/languages/haxe.min.js"),
    "text/x-hcl": () => import("./languages/terraform.js"),
    "text/x-hxml": null,
    "text/x-idl": null,
    "text/x-java": () => import("@highlightjs/cdn-assets/languages/java.min.js"),
    "text/x-julia": () => import("@highlightjs/cdn-assets/languages/julia.min.js"),
    "text/x-kotlin": () => import("@highlightjs/cdn-assets/languages/kotlin.min.js"),
    "text/x-latex": () => import("@highlightjs/cdn-assets/languages/latex.min.js"),
    "text/x-less": () => import("@highlightjs/cdn-assets/languages/less.min.js"),
    "text/x-literate-haskell": null,
    "text/x-livescript": () => import("@highlightjs/cdn-assets/languages/livescript.min.js"),
    "text/x-lua": () => import("@highlightjs/cdn-assets/languages/lua.min.js"),
    "text/x-mariadb": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-markdown": () => import("@highlightjs/cdn-assets/languages/markdown.min.js"),
    "text/x-mathematica": () => import("@highlightjs/cdn-assets/languages/mathematica.min.js"),
    "text/x-modelica": null,
    "text/x-mscgen": null,
    "text/x-msgenny": null,
    "text/x-mssql": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-mumps": null,
    "text/x-mysql": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-nix": () => import("@highlightjs/cdn-assets/languages/nix.min.js"),
    "text/x-nginx-conf": () => import("@highlightjs/cdn-assets/languages/nginx.min.js"),
    "text/x-nsis": () => import("@highlightjs/cdn-assets/languages/nsis.min.js"),
    "text/x-objectivec": () => import("@highlightjs/cdn-assets/languages/objectivec.min.js"),
    "text/x-ocaml": () => import("@highlightjs/cdn-assets/languages/ocaml.min.js"),
    "text/x-octave": null,
    "text/x-oz": null,
    "text/x-pascal": () => import("@highlightjs/cdn-assets/languages/delphi.min.js"),
    "text/x-perl": () => import("@highlightjs/cdn-assets/languages/perl.min.js"),
    "text/x-pgsql": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-php": () => import("@highlightjs/cdn-assets/languages/php.min.js"),
    "text/x-pig": null,
    "text/x-plsql": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-properties": () => import("@highlightjs/cdn-assets/languages/properties.min.js"),
    "text/x-protobuf": () => import("@highlightjs/cdn-assets/languages/protobuf.min.js"),
    "text/x-pug": null,
    "text/x-puppet": () => import("@highlightjs/cdn-assets/languages/puppet.min.js"),
    "text/x-python": () => import("@highlightjs/cdn-assets/languages/python.min.js"),
    "text/x-q": () => import("@highlightjs/cdn-assets/languages/q.min.js"),
    "text/x-rpm-changes": null,
    "text/x-rpm-spec": () => import("./languages/rpm-specfile.js"),
    "text/x-rsrc": () => import("@highlightjs/cdn-assets/languages/r.min.js"),
    "text/x-rst": null,
    "text/x-ruby": () => import("@highlightjs/cdn-assets/languages/ruby.min.js"),
    "text/x-rustsrc": () => import("@highlightjs/cdn-assets/languages/rust.min.js"),
    "text/x-sas": () => import("@highlightjs/cdn-assets/languages/sas.min.js"),
    "text/x-sass": () => import("@highlightjs/cdn-assets/languages/scss.min.js"),
    "text/x-scala": () => import("@highlightjs/cdn-assets/languages/scala.min.js"),
    "text/x-scheme": () => import("@highlightjs/cdn-assets/languages/scheme.min.js"),
    "text/x-scss": () => import("@highlightjs/cdn-assets/languages/scss.min.js"),
    "text/x-sh": () => import("@highlightjs/cdn-assets/languages/bash.min.js"),
    "text/x-slim": null,
    "text/x-smarty": null,
    "text/x-sml": () => import("@highlightjs/cdn-assets/languages/sml.min.js"),
    "text/x-solr": null,
    "text/x-soy": null,
    "text/x-spreadsheet": null,
    "text/x-sql": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-sqlite;schema=trilium": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-sqlite": () => import("@highlightjs/cdn-assets/languages/sql.min.js"),
    "text/x-squirrel": null,
    "text/x-stex": null,
    "text/x-stsrc": () => import("@highlightjs/cdn-assets/languages/smalltalk.min.js"),
    "text/x-styl": () => import("@highlightjs/cdn-assets/languages/stylus.min.js"),
    "text/x-swift": () => import("@highlightjs/cdn-assets/languages/swift.min.js"),
    "text/x-systemverilog": () => import("@highlightjs/cdn-assets/languages/verilog.min.js"),
    "text/x-tcl": () => import("@highlightjs/cdn-assets/languages/tcl.min.js"),
    "text/x-textile": null,
    "text/x-tiddlywiki": null,
    "text/x-toml": () => import("@highlightjs/cdn-assets/languages/ini.min.js"),
    "text/x-tornado": null,
    "text/x-ttcn-asn": null,
    "text/x-ttcn-cfg": null,
    "text/x-ttcn": () => import("./languages/ttcn3.js"),
    "text/x-twig": () => import("@highlightjs/cdn-assets/languages/twig.min.js"),
    "text/x-vb": () => import("@highlightjs/cdn-assets/languages/vbnet.min.js"),
    "text/x-verilog": () => import("@highlightjs/cdn-assets/languages/verilog.min.js"),
    "text/x-vhdl": () => import("@highlightjs/cdn-assets/languages/vhdl.min.js"),
    "text/x-vue": null,
    "text/x-webidl": null,
    "text/x-xu": null,
    "text/x-yacas": null,
    "text/x-yaml": () => import("@highlightjs/cdn-assets/languages/yaml.min.js"),
    "text/x-z80": null,
    "text/xml": () => import("@highlightjs/cdn-assets/languages/xml.min.js"),
}

const normalizedByMimeType: MimeRecord = {};
for (const [mimeType, loader] of Object.entries(byMimeType)) {
    const normalizedMimeType = normalizeMimeTypeForCKEditor(mimeType);
    normalizedByMimeType[normalizedMimeType] = loader;
}

export default normalizedByMimeType;
